<?php

/**
 * EntitytypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EntitytypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return EntitytypeTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Entitytype');
    }
}