<?php

/**
 * PersonPersonRelationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PersonPersonRelationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PersonPersonRelationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PersonPersonRelation');
    }
}