<?php

/**
 * PersonPaymentRelationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PersonPaymentRelationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PersonPaymentRelationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PersonPaymentRelation');
    }
}