<?php

/**
 * PersonActivityRelationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PersonActivityRelationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PersonActivityRelationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PersonActivityRelation');
    }
}