<?php

/**
 * RegannexTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RegannexTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RegannexTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Regannex');
    }
}