<?php

/**
 * ServicePersonRelationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ServicePersonRelationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ServicePersonRelationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ServicePersonRelation');
    }
}