<?php

/**
 * TaxPersonRelationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TaxPersonRelationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TaxPersonRelationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TaxPersonRelation');
    }
}