<?php

/**
 * TaxTaxRelationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TaxTaxRelationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TaxTaxRelationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TaxTaxRelation');
    }
}